### ISSUE TITLE
Support interception of request/response

### ISSUE THREAD

**Issue by roytmana** [elastic/elasticsearch-transport-wares#28]
It would be nice if it were possible to provide some sort of interception for request/response.
The use cases are 

- Verify/enrich request before processing (permissions, mandatory filters ...)
- Verify/enrich response (ex: compare _source.owner with logged in user)
- Return custom error messages. In my case I need to suppress error message disclosing actual exception going back to the client and return just code and no message or a generic message

As a hack for responce interception I could provide a custom implementation of ServletRestChannel if NodeServlet supported ability to specify implementation class in init params or something like this

**Comment by dadoonet** [comment]
Closing. We can revisit it depending on the outcome from https://github.com/elastic/elasticsearch/issues/12721
